on:
 - push
 - pull_request
env:
  LATEST_VERSION: 0.38.0

name: Validate
jobs:
  conftest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: install conftest
      run: wget -O - 'https://github.com/open-policy-agent/conftest/releases/download/v${{ env.LATEST_VERSION }}/conftest_${{ env.LATEST_VERSION }}_Linux_x86_64.tar.gz' | tar zxvf -

    - name: unit-test
      run: ./conftest verify ./
    - name: test
      run: ./conftest test ./dev/deployment.yaml